baseurl = "https://alvinthomas.github.io/"
title = "Alvin G. Thomas"
copyright = "&copy; 2017 Alvin G. Thomas"
theme = "hugo-academic"
enableEmoji = true
footnotereturnlinkcontents = "<sup>^</sup>"

# Enable comments by entering your Disqus shortname
disqusShortname = "alvinthomas" # statsnips

# Enable analytics by entering your Google Analytics tracking ID
googleAnalytics = "UA-99083233-1" # UA-99083233-1

# Default language to use (if you setup multilingual support)
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false

[blackfriday]
  hrefTargetBlank = true

[params]
  name = "Alvin G. Thomas"
  role = "Transplantation Epidemiologist"
  organization = "Epidemiology Research Group in Organ Transplantation"
  organization_url = "https://transplantepi.org/"
  gravatar = false  # Get your avatar from Gravatar.com? (true/false)
  avatar = "headshot.png"  
  email = "alvin@jhmi.edu"
  address = "Baltimore, MD, USA"
  #office_hours = ""
  #phone = ""
  #skype = ""
  telegram = ""
  twitter = "alvinthomas13"
  github = "alvinthomas"
  linkedin = "alvinthomas13"

  # Enable Keybase in Contact section by entering your keybase.io username.
  keybase = ""

  # Date format (refer to Go's date format: http://flippinggodateformat.com )
  #   Examples: "Mon, Jan 2, 2006" or "2006-01-02"
  date_format = "Mon, Jan 2, 2006"

  # Enable global LaTeX math rendering?
  #   If false, you can enable it locally on a per page basis.
  math = false

  # Highlight.js options
  #   highlight
  #     Enable global source code highlighting?  If false, you can
  #     override it for a particular page in that page's preamble.
  #
  #     Example: highlight = true
  #
  #   highlight_languages
  #     Add support for highlighting additional languages. Support for
  #     languages mentioned here will be included in all pages. You
  #     can also set this variable for a particular page in that
  #     page's preamble.
  #
  #     Example: highlight_languages = ["go", "lisp", "ocaml"]
  #
  #   highlight_style
  #     Choose a different CSS style for highlighting source
  #     code. Setting this option in a page's preamble has no
  #     effect.
  #
  #     Example: highlight_style = "github-gist"
  #
  #   highlight_version
  #     Choose the version of highlight.js you want. Setting this
  #     option in a page's preamble has no effect.
  #
  #     Example: highlight_version = "9.9.0"
  #
  #   For the list of supported languages, styles, and versions, see:
  #   https://cdnjs.com/libraries/highlight.js/
  #
  #   For more info on the highlighting options, see:
  #   https://gcushen.github.io/hugo-academic-demo/post/writing-markdown-latex/#highlighting-options
  highlight = true
  highlight_languages = []
  # highlight_style = "github"
  # highlight_version = "9.9.0"

  # Enable native social sharing buttons?
  sharing = true

  # Link custom CSS and JS assets
  #   (relative to /static/css and /static/js respectively)
  custom_css = []
  custom_js  = []

  # Publication types.
  #   Used to categorize publications.
  #   The index of the publication type in the list is used as its unique numerical identifier.
  #   The numeric ID is used in a publication's frontmatter to categorize it.
  #   The language can be edited below.
  #   For multi-lingual sites, copy this block to each language section at the end of this file.
  publication_types = [
    'Uncategorized',  # 0
    'Conference proceedings',  # 1
    'Journal',  # 2
    'Work in progress',  # 3
    'Technical report',  # 4
    'Book',  # 5
    'Book chapter'  # 6
  ]

  # Social/Academic Networking
  #
  # Icon pack "fa" includes the following social network icons:
  #
  #   twitter, weibo, linkedin, github, facebook, pinterest, google-plus,
  #   youtube, instagram, soundcloud
  #
  #   For email icon, use "fa" icon pack, "envelope" icon, and
  #   "mailto:your@email.com" as the link.
  #
  #   Full list: https://fortawesome.github.io/Font-Awesome/icons/
  #
  # Icon pack "ai" includes the following academic network icons:
  #
  #   google-scholar, arxiv, orcid, researchgate, mendeley
  #
  #   Full list: https://jpswalsh.github.io/academicons/


  [[params.social]]
    icon = "google-scholar"
    icon_pack = "ai"
    link = "https://scholar.google.com/citations?user=_vIM38AAAAAJ&hl"

  [[params.social]]
    icon = "orcid"
    icon_pack = "ai"
    link = "https://orcid.org/0000-0003-4911-8192"
    
  [[params.social]]
    icon = "researchgate"
    icon_pack = "ai"
    link = "https://www.researchgate.net/profile/Alvin_Thomas7"

  [[params.social]]
    icon = "mendeley"
    icon_pack = "ai"
    link = "https://www.mendeley.com/profiles/alvin-thomas2"
    
  [[params.social]]
    icon = "publons"
    icon_pack = "ai"
    link = "https://publons.com/author/1271274/alvin-g-thomas"
    
  [[params.social]]
    icon = "pubmed"
    icon_pack = "ai"
    link = "https://www.ncbi.nlm.nih.gov/pubmed/?term=Thomas%2C%20Alvin%20G%5BFull%20Author%20Name%5D&cmd=DetailsSearch"

  [[params.social]]
    icon = "impactstory"
    icon_pack = "ai"
    link = "https://profiles.impactstory.org/u/0000-0003-4911-8192"

  [[params.social]]
    icon = "twitter"
    icon_pack = "fa"
    link = "https://twitter.com/alvinthomas13"

  [[params.social]]
    icon = "github"
    icon_pack = "fa"
    link = "https://github.com/alvinthomas"

  [[params.social]]
    icon = "linkedin"
    icon_pack = "fa"
    link = "https://www.linkedin.com/in/alvinthomas13/"  
    
  [[params.social]]
    icon = "envelope"
    icon_pack = "fa"
    link = "mailto:alvin@jhmi.edu"


# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[menu.main]]
  name = "Home"
  url = "#about"
  weight = 1

[[menu.main]]
  name = "Publications"
  url = "#publications_selected"
  weight = 2

[[menu.main]]
  name = "Projects"
  url = "#projects"
  weight = 3

[[menu.main]]
  name = "Contact"
  url = "#contact"
  weight = 4

# Taxonomies.
[taxonomies]
  tag = "tags"
  category = "categories"
  publication_type = "publication_types"

# Languages
#   Create a [languages.X] block for each language you want, where X is the language ID.

# Configure the English version of the website.
[languages.en]
  languageCode = "en-us"
